### ISSUE TITLE
Social media urls to add to your legislators data set

### ISSUE THREAD

**Issue by pardery** [unitedstates/unitedstates.github.io#4]
Hello,

I work with the Library of Congress, and I am using your 'legislators-current' and 'legislators-social-media' yaml files to facilitate scoping for our US Congress web archive collection.  Thanks for the data!

As it turns out, you had a good chunk of social media sites that we were missing.  However, we also seem to have a descent amount of data that you are missing.  I have a .json file that lists all social media sites that we have and you don't, per bioguide ID.  Who should I send it to?

Thanks,
Phil

**Comment by dwillis** [comment]
Thanks for your interest! If I could ask you to open an issue in the [congress-legislators repo](https://github.com/unitedstates/congress-legislators/issues), that would be awesome. One thing to bear in mind: we only list official office social media accounts, not those that are considered personal to the officeholder.

But it's worth taking a look - if you can put the .json file on a server someplace (or in a gist, even) and open an issue on congress-legislators that would be a great start.

**Comment by pardery** [comment]
Thanks @dwillis!  I created a new ticket [here](https://github.com/unitedstates/congress-legislators/issues/293) and placed the data in [this gist](https://gist.github.com/pardery/84fc56c836c4b1f02708)
