### ISSUE TITLE
Importing legislator data into Wikidata

### ISSUE THREAD

**Issue by thinkcontext** [unitedstates/unitedstates.github.io#7]
Building on the work of @harej of adding Wikidata ids to legislators, I've written a simple script to add some of the data in the legislator repository into Wikidata.  Its pretty basic stuff, the OpenSecrets id, Facebook, Twitter, and Youtube Channel id. 

https://github.com/thinkcontext/congress-wikidata

Obviously there are many more facts that are part of this project that could be pushed into Wikidata, is there interest in adopting this?

**Comment by JoshData** [comment]
Please open an issue at https://github.com/unitedstates/congress-legislators. Thanks.
