### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by ericj-hernandez** [unitedstates/unitedstates.github.io#8]
Hi there! I'm an aspiring data practitioner and have found this repository very useful.

As a suggestion (not sure how to do it myself - yet!), it would be extremely helpful if **'congress-legislators/legislators-current'** and **'congress-legislators/legislators-historical'** had _'terms/current/...'_ and _'terms/most-recent/...'_ groups in their yaml structures in order to smooth the logic for gathering current/most recent term information from the files.

**Comment by JoshData** [comment]
Please head over to https://github.com/unitedstates/congress-legislators. Thanks. :)
